### ISSUE TITLE
Stack error

### ISSUE THREAD

**Issue by jonahcullen** [apcamargo/RNAsamba#16]
Hello, I am attempting to use `rnasamba classify` with the provided human training data as

```
rnasamba classify \
    -v 1 \
    class_m029.human_train.tsv \
    td_non_code_sized.gff \
    full_length_weights.hdf5
```

which returns the following error

```
Using TensorFlow backend.
[1/4] Computing network inputs.
Traceback (most recent call last):
  File "/home/fried255/shared/.local/conda/envs/rnasamba/bin/rnasamba", line 11, in <module>
    sys.exit(cli())
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/cli.py", line 158, in cli
    args.func(args)
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/cli.py", line 30, in classify
    args.fasta_file, args.weights, verbose=args.verbose
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/core/model.py", line 48, in __init__
    self.input = RNAsambaInput(fasta_file)
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/core/inputs.py", line 59, in __init__
    self.orf_indicator_input = self.get_orf_indicator_input()
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/core/inputs.py", line 75, in get_orf_indicator_input
    return sequences.orf_indicator(self._orfs, self.maxlen)
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/rnasamba/core/sequences.py", line 60, in orf_indicator
    orf_indicator = np.stack(orf_indicator)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/fried255/shared/.local/conda/envs/rnasamba/lib/python3.7/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

I have the most recent version of rnasamba (0.2.4), with TensorFlow (1.15.0), and h5py (2.10.0).

Thank you very much for your time and providing this most excellent resource!

**Comment by jonahcullen** [comment]
Please disregard! I was accidentally inputing my GFF as opposed to the FASTA. Apologies!
